#ifndef LV_CONF_H
#define LV_CONF_H
#define LV_COLOR_DEPTH 16
#define LV_USE_STDLIB_MALLOC LV_STDLIB_CLIB
#define LV_USE_STDLIB_STRING LV_STDLIB_CLIB
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_CLIB
#define LV_USE_CANVAS 1
#define LV_USE_LOG 0
#define LV_USE_OS LV_OS_NONE
#define LV_DRAW_SW_SUPPORT_RGB565 1
#endif
